### ISSUE TITLE
it's not possible to bundle instana with webpack

### ISSUE THREAD

**Issue by BeiNacht** [instana/nodejs-sensor#115]
Hi, it's not possible to bundle instana nodejs sensor with webpack.
`Cannot find module './instrumentation/control_flow/bluebird'`

https://github.com/instana/nodejs-sensor/blob/master/src/tracing/index.js

Webpack has tough problems with this kind of dynamic module loading

**Comment by basti1302** [comment]
Hi there,

very true, it is not possible to bundle Instana with Webpack and it also wouldn't make any sense at all :-)

This npm package `instana-nodejs-sensor` is (as the name suggests) strictly intended to monitor **Node.js** server components. It is not meant to monitor client side JavaScript running in the browser. Check out https://docs.instana.io/products/website_monitoring/#installation to learn how to integrate Instana's website monitoring capabilities with your JavaScript app running in the browser.

Have a great day

  Bastian

PS: Closing this, if you have any more questions, feel free to reach out at https://support.instana.com/hc/en-us/requests/new
