### ISSUE TITLE
Report unhandledRejection events

### ISSUE THREAD

**Issue by geekflyer** [instana/nodejs-sensor#134]
Please also report unhandledRejection events (i.e. rejected promises)(https://nodejs.org/api/process.html#process_event_unhandledrejection ).

**Comment by basti1302** [comment]
Hi,

could you please file this as a feature request via https://support.instana.com/hc/en-us/requests/new ?

Thanks

  Bastian

**Comment by basti1302** [comment]
For the record, this has landed in `@instana/collector@1.66.0`.
