### ISSUE TITLE
update to @instana/collector broke our application

### ISSUE THREAD

**Issue by albertlinga** [instana/nodejs-sensor#138]
previously we are referencing instana-nodejs-sensor. After our CI / CD ran npm install yesterday it errored out saying the package is renamed to @instana/collector. I have updated our application to reference the new package and followed the instructions here. Unfortunately I'm getting errors after the agent is instantiated. 

TypeError: Cannot read property 'timeBetweenHealthcheckCalls' of undefined
    at Object.exports.activate (/usr/src/app/node_modules/@instana/core/src/metrics/healthchecks.js:25:46)
    at /usr/src/app/node_modules/@instana/core/src/metrics/index.js:31:31
    at Array.forEach (<anonymous>)
    at Object.exports.activate (/usr/src/app/node_modules/@instana/core/src/metrics/index.js:29:24)
    at Object.exports.activate (/usr/src/app/node_modules/@instana/collector/src/metrics/index.js:15:21)
    at Object.enter (/usr/src/app/node_modules/@instana/collector/src/announceCycle/agentready.js:28:21)
    at Object.transitionTo (/usr/src/app/node_modules/@instana/collector/src/announceCycle/index.js:25:34)
    at /usr/src/app/node_modules/@instana/collector/src/announceCycle/announced.js:23:21
    at callbackWrappedForAtMostOneExecution (/usr/src/app/node_modules/@instana/core/src/util/atMostOnce.js:27:27)

**Comment by basti1302** [comment]
I‘m sorry that this change caused issues. I‘ll look into this immediately. If you need an immediate workaround you could pin the dependency to version 1.64.0 by running `npm install —save instana-nodejs-sensor@1.64.0` in your project.

**Comment by basti1302** [comment]
A proper fix for this has been published with version 1.65.1 of @instana/collector, so the workaround I outlined above is no longer necessary. Again, sorry for the trouble this has caused.
