### ISSUE TITLE
nodejs sensor triggers deprecation warning in Fastify

### ISSUE THREAD

**Issue by beep-boop-beep** [instana/nodejs-sensor#163]
There is an issue with the instana nodejs sensor and Fastify:

When the instana-nodejs-sensor is activated and this is executed 
https://github.com/instana/nodejs-sensor/blob/4a9e07fbc46db384f312d6139e2d6679423b28ef/packages/core/src/tracing/instrumentation/frameworks/fastify.js#L100

this deprecation warning in Fastify is triggered over and over:

`Warning: basePath is deprecated. Use prefix instead. See: https://www.fastify.io/docs/latest/Server/#prefix`

**Comment by beep-boop-beep** [comment]
PR: https://github.com/instana/nodejs-sensor/pull/164

**Comment by basti1302** [comment]
Closed via #164, efb7063 and fix released in 1.71.2.
