### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by jhorowitz** [instana/nodejs-sensor#21]
Would it be possible to convert this codebase to typescript? I'd be happy to do the heavy lifting and make a pull request. It'd allow type safety and also make the codebase easier to reason about / introspect.

**Comment by bripkens** [comment]
Converting it to TypeScript sounds like a useful change, though not a necessary one (it is not a Instana priority at all). Additionally, it is a type of change which would require a lot of thorough testing.

I am interested, why would you do this? AFAIK you are not an Instana user and doing this is a ton of work. What is in it for you?  Considering your GitHub profile description, the only possible reason that I can see is security (research) 😏

**Comment by jhorowitz** [comment]
Sorry about the delay. My github notifications have been weird lately.

Ahaha. My github needs some updating. I'm currently working at a company that's auditing Instana as a potential solution but we've been having a few technical issues. I figured lending coding support was the fastest way to come to a solution.

**Comment by bripkens** [comment]
If you have some technical issues, then the best way to approach this would be to open a ticket for these issues. Because that way, we might be able to find a direct solution to your problem, instead of a large refactoring, which may or may not solve your issue. 

You can open a ticket on [1]. 

[1] https://support.instana.com/hc/en-us/requests/new

**Comment by jhorowitz** [comment]
That's fair. I already opened a ticket but was told this would probably not be solved within my timeline. I figured that was probably because of limited engineering bandwidth.

**Comment by basti1302** [comment]
Closing this. There will be no conversion to TS in the foreseeable future.

**Comment by rene-leanix** [comment]
@basti1302, any chance that [TypeScript type annotations could be added](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) to this project? This would help a lot when using the agent, both from within TypeScript projects, but also from JavaScript-projects that have type-checking enabled.

**Comment by basti1302** [comment]
Hi Rene, this would be a feature request. Please do not use Github issues for feature request (let alone old closed issues). Instead, please file these at https://automation-management.ideas.ibm.com/?project=INSTANA.

Actually, there is already a request for typescript definitions, so you can add your vote for this here: https://automation-management.ideas.ibm.com/ideas/INSTANA-I-300

Kind regards

  Bastian
