### ISSUE TITLE
Get rid of bunyan package in dependencies

### ISSUE THREAD

**Issue by ana-ya** [instana/nodejs-sensor#225]
Let's replace [bunyan](https://www.npmjs.com/package/bunyan) on something freshly because the last update was 3 years ago. Moreover, it contains packages with vulnerability issues [mimimist](https://www.npmjs.com/advisories/1179).

**Comment by basti1302** [comment]
Hey Ana,

thanks for the suggestion. I might be inclined to replace bunyan at some point, but to be honest, it is not high on my priority list. 

You can already replace the logger that is actually used via `instana.setLogger`, see  https://docs.instana.io/ecosystem/node-js/api/#setting-the-logger-after-initialization.

As for the vulnerability, this is how the dependency path (including versions) looks like:
`@instana/collector`-> `bunyan@^1.8.12`-> `mv@~2` (can be resolved to `mv@2.1.1`) -> `mkdirp@~0.5.1` (can be resolved to >= `mkdirp@0.5.3`) -> `minimist@^1.2.5`. The vulnerability you mentioned does not affect `minimist@1.2.5`, only versions up to 1.2.2 are affected. 

If a vulnerable version of `minimist` appears in your transitive dependencies and you think it is the fault of `@instana/collector` you might need to update transitive dependencies in your package-lock.json. Running `npm update --depth 999 @instana/collector` or maybe `npm update --depth 999 mkdirp` might help. See this [commit](https://github.com/instana/nodejs-sensor/commit/fef74dabb66020d8e1a6c7b248afa6fc8431c223) where I fixed the dependencies in our own package lock files on the very day the vulnerability was published.

Please also not that we run `npm audit --production` for every package on every build, thus we can guarantee that we do not introduce dependencies with known vulnerabilities into your code base.

Apart from that, assuming we do replace bunyan at some point, do you have any suggestions for what to replace bunyan with? Pino would probably be an ovbvious candidate.

**Comment by ana-ya** [comment]
Thank you, Bastian, for your useful response. 

Sure I've updated as you mentioned it.

Regarding replacing, firstly we also considered [pino](https://www.npmjs.com/package/pino) as well, but after grooming we have decided to go with [winston](https://www.npmjs.com/package/winston).

**Comment by basti1302** [comment]
Hi Anastasia,

I will close this one for now. I might replace Bunyan at some point if I have some free cycles, but it's likely to happen anytime soon, so there is little benefit in keeping this issue open. I'm glad you could solve your dependency/vulnerability issue.

Kind regards

  Bastian
