### ISSUE TITLE
Support node-rdkafka

### ISSUE THREAD

**Issue by Tapppi** [instana/nodejs-sensor#24]
Hey,

The best supported and highest performing node kafka library at the moment seems to be https://github.com/Blizzard/node-rdkafka. Any chance we could get support for it in this sensor? I might look at doing it myself, any pointers to get started?

**Comment by bripkens** [comment]
Hey @Tapppi,

supporting node-rdkafka sounds like a good plan. Instrumenting libraries is mostly straightforward. You could take a look at the existing kafka instrumentation [1] as well as the integration tests [2]. Looking forward to your contribution! ❤️ 

[1] https://github.com/instana/nodejs-sensor/blob/master/src/tracing/instrumentation/kafka.js
[2] https://github.com/instana/nodejs-sensor/blob/master/test/tracing/kafka_test.js

**Comment by basti1302** [comment]
Since we never heard back from Tapppi, I'll close this for now.
