### ISSUE TITLE
Collector is missing linked CHANGELOG.md

### ISSUE THREAD

**Issue by janpio** [instana/nodejs-sensor#243]
https://github.com/instana/nodejs-sensor/blob/main/packages/collector/CHANGELOG.md does not exist.

**Comment by basti1302** [comment]
https://github.com/instana/nodejs-sensor/blob/main/CHANGELOG.md exists. Does that help?

**Comment by basti1302** [comment]
The title says "linked changelog". I wonder which link you refer to. Care to provide a bit more context?

**Comment by basti1302** [comment]
Nevermind, found it. I guess you were refering to this: https://github.com/instana/nodejs-sensor/commit/9c0d588b300ad670fde03026323d917f1f843c7c ?

**Comment by janpio** [comment]
Sorry, yes - I forgot to link to the actual source of the problem. I indeed meant the collector README at https://github.com/instana/nodejs-sensor/tree/main/packages/collector
