### ISSUE TITLE
API doesn't list latest lambda layer version

### ISSUE THREAD

**Issue by deepakthankachan** [instana/nodejs-sensor#262]
Using latest lambda layer [v1.103.0](https://www.instana.com/docs/ecosystem/aws-lambda/nodejs/#manually-wrapping-the-handler) gives the following warning:
`WARN Invalid configuration: config.tracing.http.extraHttpHeadersToCapture is not an array, the value will be ignored:`
Is the versions list for lambda layer on your webpage not up to date? Latest Node module version for @instana/aws-lambda doesn't cause the same warning as it has the fix for this bug looking at the change log. If the lambda layer version isn't updated, when is it likely to be published.

Regards,
Deepak

**Comment by basti1302** [comment]
Hi Deepak,

thanks for the report. The info in our documentation was indeed lagging behind. We automatically publish a new Lambda layer everytime we publish a new version of `@instana-aws/lambda`. The latest layers are here:

 | Region           | ARN  | `@instana/aws-lambda` Version |
 | ---------------- | ---- | ----------------------------- |
| `ap-northeast-1` | `arn:aws:lambda:ap-northeast-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `ap-northeast-2` | `arn:aws:lambda:ap-northeast-2:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `ap-south-1`     | `arn:aws:lambda:ap-south-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `ap-southeast-1` | `arn:aws:lambda:ap-southeast-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `ap-southeast-2` | `arn:aws:lambda:ap-southeast-2:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `ca-central-1`   | `arn:aws:lambda:ca-central-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `eu-central-1`   | `arn:aws:lambda:eu-central-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `eu-north-1`     | `arn:aws:lambda:eu-north-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `eu-west-1`      | `arn:aws:lambda:eu-west-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `eu-west-2`      | `arn:aws:lambda:eu-west-2:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `eu-west-3`      | `arn:aws:lambda:eu-west-3:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `sa-east-1`      | `arn:aws:lambda:sa-east-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `us-east-1`      | `arn:aws:lambda:us-east-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `us-east-2`      | `arn:aws:lambda:us-east-2:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `us-west-1`      | `arn:aws:lambda:us-west-1:410797082306:layer:instana-nodejs:35` | v1.106.4 |
| `us-west-2`      | `arn:aws:lambda:us-west-2:410797082306:layer:instana-nodejs:35` | v1.106.4 | 

I've updated the docs in the meantime.
