### ISSUE TITLE
ioredis support

### ISSUE THREAD

**Issue by schmod** [instana/nodejs-sensor#30]
Would it be possible to add support for [ioredis](https://github.com/luin/ioredis) instrumentation in addition to the recently-added support for [node_redis](https://github.com/NodeRedis/node_redis)?

**Comment by bripkens** [comment]
Hey @schmod ✋,

ioredis support is possible. It even seems as if it follows a similar implementation. Do you want to give building an instrumentation a try?

Cheers!

**Comment by bripkens** [comment]
ioredis support is now released @schmod in `1.33.0`. Sorry for the delay!

**Comment by schmod** [comment]
Many thanks!
