### ISSUE TITLE
Automatically mask basic-auth url credentials 

### ISSUE THREAD

**Issue by chatko** [instana/nodejs-sensor#327]
In the context of a node runtime, some application dependencies that are using a legacy basic-auth in the URL may get exposed in (plain-text) within an account. 

For example, a call such as: 
`https://username:password@some.domain.com/api/health `

May expose the `username:password`.  We'd like a regex to detect this well known pattern and mask the sensitive information in the agent. This is already happening within other runtimes (java/go) 

Instana pointed to this area for a fix: 
https://github.com/instana/nodejs-sensor/blob/main/packages/core/src/tracing/instrumentation/protocols/httpClient.js#L137

**Comment by basti1302** [comment]
@chatko This has landed in version 1.125.0.
