### ISSUE TITLE
Capture Express route path

### ISSUE THREAD

**Issue by schmod** [instana/nodejs-sensor#35]
It would be nice if Express (http server) spans could include information about the route path so I can use that path (instead of the "raw" URL) to view traces in the Instana GUI.  

For example, Instana currently captures requests that look like `/people/1234`, and I need to manually configure Endpoints in the Instana GUI for every parameterized route in all of my applications.

Instead, I'd like for Instana's NodeJS sensor to capture the parameterized [route path](https://expressjs.com/en/4x/api.html#req.route) (ie. `/people/:id`) for each request, and have the option to utilize that path instead of the raw URL when mapping endpoints (and viewing traces) in the Instana GUI.

**Comment by bripkens** [comment]
This is one of the ideas that we are currently preparing internally for automatic endpoint identification. I am not yet sure though how we could respect and correctly report on nested routers and middlewares in these scenarios. Do you have an idea how this could be done?

**Comment by bripkens** [comment]
This landed in `1.43.0` 🍾

**Comment by tcelestino** [comment]
@bripkens will it works when using Instana Collector in AWS Fargate? 

I added Instana in my Dockerfile and Instana works, but route path didn't work in dashboard 

![Screenshot from 2021-03-19 12-02-03](https://user-images.githubusercontent.com/190265/111800671-f28bd400-88aa-11eb-8b83-26ad6a0c0680.png)
*routes on Instana's dashboard*

If I analyze the calls, the correctly route path is there.

**Comment by basti1302** [comment]
Please do not report issues in Github issues that are already closed. Instead, open a ticket either at https://support.instana.com/hc/en-us/requests/new or by sending an e-mail to support@instana.com.

Thanks.

PS: The routes you are showing there have a placeholder (`:apiVersion`) which basically proves that the feature discussed here works. There is no difference with respect to URL/route capturing, whether you run Node.js on a host or in Fargate.
