### ISSUE TITLE
Proposal: drop v8-profiler dependency

### ISSUE THREAD

**Issue by cjihrig** [instana/nodejs-sensor#47]
`v8-profiler` appears to be unmaintained, and it triggers nsp vulnerabilities via:

```
instana-nodejs-sensor@1.37.0 > v8-profiler@5.7.0 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3 
```

We've been adding nsp exceptions on our repos like [this](https://github.com/joyent/webconsole-instances/blob/master/app/.nsprc), but it's far from ideal.

Furthermore, it appears that `v8-profiler` is unnecessary on the newest versions of Node due to the [`inspector`](https://nodejs.org/api/inspector.html) core module.

Perhaps in the future a semver major release could drop `v8-profiler` and adopt Node's inspector module?

**Comment by bripkens** [comment]
Hi @cjihrig,

instead of removing it, we migrated to `@risingstack/v8-profiler`. This has the additional benefit of making proper use of `node-pre-gyp`. The version without security vulnerabilities is released as `1.37.1`.

Cheers,

/ben
