### ISSUE TITLE
Can't enable tracing.

### ISSUE THREAD

**Issue by longseespace** [instana/nodejs-sensor#8]
Can't get `tracing` feature working. Error message:

```
{"name":"instana-nodejs-sensor","hostname":"platform-2337947661-4hs1r","pid":6,"module":"tracing","level":40,"msg":"Could not enable tracing feature due to an error while loading async-hook { error: \n   { Error: Cannot find module 'async-hook'\n       at Function.Module._resolveFilename (module.js:470:15)\n       at Function.Module._load (module.js:418:25)\n       at Function.Module._load (/tmp/node_modules/instana-nodejs-sensor/src/util/requireHook.js:13:34)\n       at Module.require (module.js:498:17)\n       at require (internal/module.js:20:19)\n       at checkPrerequisites (/tmp/node_modules/instana-nodejs-sensor/src/tracing/index.js:47:5)\n       at Object.exports.init (/tmp/node_modules/instana-nodejs-sensor/src/tracing/index.js:11:27)\n       at start (/tmp/node_modules/instana-nodejs-sensor/src/index.js:17:24)\n       at Object.<anonymous> (/app/dist/index.js:27:35)\n       at Module._compile (module.js:571:32) code: 'MODULE_NOT_FOUND' } }","time":"2017-05-29T04:04:54.577Z","v":0}
```

I can see `async-hook` is declared as _optional dependency_. Should I have to change my build scripts? Please help.

**Comment by bripkens** [comment]
@longseespace: `async-hook` needs to be installed in order to use tracing. It is marked as optional as metric gathering is supported without `async-hook`.

**Comment by longseespace** [comment]
Thanks, @bripkens. I manually installed `async-hook` and tracing was enabled successfully. I can see `event-loop-stats`, `gcstats.js` and `v8-profiler` are also in `optionalDependencies`. Do I have to install them as well? Also, how can I have `health-check` enabled?

**Comment by bripkens** [comment]
@longseespace: You can install those to get a few more features, i.e. event loop and garbage collection statistics as well as CPU profiling support. NPM / yarn should automatically install these dependencies. Why do you have do add them manually?

> Also, how can I have health-check enabled?

Health checks are automatically recognized when your application is using [admin](https://www.npmjs.com/package/admin) in combination with [admin-plugin-healthcheck](https://www.npmjs.com/package/admin-plugin-healthcheck).

**Comment by longseespace** [comment]
Oh sorry, my bad. Only `async-hook` not being installed automatically. The rest are working fine. Thanks. I'm closing this issue now
