### ISSUE TITLE
Configure Host on Kubernetes

### ISSUE THREAD

**Issue by aldafu** [instana/nodejs-sensor#92]
When having the agent deployed through Helm (as described here:
https://github.com/instana/instana-helm-chart) what's the best way to configure the `agentHost` setting? The default `localhost` won't do since that is local to the pod and the agent is running in a different pod on the same node.

**Comment by aldafu** [comment]
After a while the sensor will switch from `unannounced` to `announced` and then it works.

**Comment by basti1302** [comment]
Sorry, I didn't see this in time. Seems you have already been able to figure it out. Please use https://support.instana.com/hc/en-us/requests/new to file a support requests in the future, thanks.
